<Project>

  <PropertyGroup Label="Repo">
    <RepoRootPath>$(MSBuildThisFileDirectory)</RepoRootPath>
    <Authors>Ziyou Zheng and contributors</Authors>
    <Company>Microsoft</Company>
    <Product>Microsoft.Azure.Cosmos.OData</Product>
    <Copyright>Copyright © Microsoft Corporation. Licensed under the MIT License.</Copyright>
    <PackageProjectUrl>https://github.com/z26zheng/azure-documentdb-odata-sql</PackageProjectUrl>
    <RepositoryUrl>https://github.com/z26zheng/azure-documentdb-odata-sql.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>odata cosmos cosmosdb sql translate query aspnetcore webapi</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Label="Versioning">
    <VersionPrefix>4.1.1</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == '' and '$(GITHUB_REF_TYPE)' != 'tag'">alpha.1</VersionSuffix>
    <FileVersion>4.0.0.0</FileVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Label="Build">
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;CS1591;CA1303;CA1062</NoWarn>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <PropertyGroup Label="Source Link" Condition="'$(IsPackable)' == 'true' or '$(IsPackable)' == ''">
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Label="Source Link" Condition="'$(IsPackable)' != 'false'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Label="Package README" Condition="'$(IsPackable)' == 'true'">
    <None Include="$(RepoRootPath)README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
